### ISSUE TITLE
[Speed Focus Mode] Give Me More Time button

### ISSUE THREAD

**Issue by deed02392** [glutanimate/speed-focus-mode#2]
## Which add-on is affected?

Speed Focus Mode

## Prerequisite checklist

- [X ] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [X ] Did you check the add-on description on AnkiWeb for known issues?
- [ X] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

It would be great to have a hotkey we can hit to say 'give me more time'.

Sometimes I get a word that I am pretty sure I will remember if I just get a couple more seconds to think about it, and in those moments it would be nice to delay the answer reveal. Something like tapping ` (because it's next to the answer hotkeys) adding 2 seconds to whatever the currently active timer is would be ideal.

## Version information

**Anki**

Version 2.1.9 (ae67c976)
Qt 5.12.1 PyQt 5.11.3

**System**

- Operating system: macOS
- Version: Mojave

**Comment by glutanimate** [comment]
@deed02392 @tedsoft @Cupbox

I just pushed a new beta release with this feature integrated (among other things). If you guys have the time, I'd love for you to give it a try and let me know what you think!:

https://github.com/glutanimate/speed-focus-mode/releases/tag/v0.4.0-beta.1

**Comment by tedsoft** [comment]
Good job @glutanimate , I'll use it for some time.
any bugs or new ideas  I'll tell you.

**Comment by tedsoft** [comment]
Good job @glutanimate 
the new option is great!
I'll use it for some time. any bugs or new ideas I'll tell you.

**Comment by Cupbox** [comment]
Works perfectly. 
It's now incompatible with the Night Mode addon though.

**Comment by glutanimate** [comment]
Thanks for the feedback, guys! Glad to hear it's working well.

@Cupbox Sorry to hear that. It seems like it's hard to avoid interactions with NM these days when modifying the reviewer. Would you mind opening a new issue for this? And a few questions that could help with the troubleshooting process:

- With NM installed, does Speed Focus not work at all or is there only a particular feature that's not behaving as expected (e.g. the pause button)?
- Can you reliably fix the issue by either disabling "reviewer styling" in NM's settings or disabling NM entirely via Tools → Add-ons?
- Which version of Anki and NM are you using?

If you could add your answers to these to the bug report, I'd very much appreciate that!

I'm closing this issue report for now as the pause button seems to be working fine save for this potential add-on conflict.
