### ISSUE TITLE
Interference with AnkiConnect

### ISSUE THREAD

**Issue by Cupbox** [glutanimate/speed-focus-mode#23]
#### Problem description

When using [Yomichan](https://github.com/FooSoft/yomichan) with [AnkiConnect](https://ankiweb.net/shared/info/2055492159), pressing **view added note** in the Yomichan extension opens the browser but does not browse to the card in question with the beta speed focus mode on github. The old version on AnkiWeb works fine.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X] I've restarted Anki to see if it helps
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X] I've tried to disable other add-ons to see if there are any interactions present
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

Version 2.1.21 (f1734a47)

##### If you are using Anki 2.1
    
    Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-03-06 20:19:43
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AnkiConnect ['2055492159', 2020-03-06T08:46, 'None', '']
    Speed Focus Mode ['speed_focus_mode', 2019-06-29T03:35, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    2055492159
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by glutanimate** [comment]
Thanks a bunch for the report! This should now be fixed in the `main` branch and find its way into the next release (which will go live on [09/09 on Patreon](https://www.patreon.com/posts/long-overdue-55374245) and be posted to AnkiWeb later this fall.
