### ISSUE TITLE
Speed focus (add more time version) conflicting w/ heatmap add-on

### ISSUE THREAD

**Issue by jaredagordon** [glutanimate/speed-focus-mode#34]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

When add on is enabled, I cannot select heatmap days on browser

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-12-20 08:09:53
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 547, in _onBridgeCmd
  File "</Applications/Anki 2.1.35.app/Contents/MacOS/decorator.pyc:decorator-gen-70>", line 2, in _linkHandler
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/jaredgordon/Library/Application Support/Anki2/addons21/review_heatmap/links.py", line 81, in heatmapLinkHandler
    invokeBrowser(arg)
  File "/Users/jaredgordon/Library/Application Support/Anki2/addons21/review_heatmap/links.py", line 108, in invokeBrowser
    browser.form.searchEdit.lineEdit().setText(search)
AttributeError: 'NoneType' object has no attribute 'form'

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```


```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Catalina
- version:10.15.7

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*
![image](https://user-images.githubusercontent.com/60485584/102718461-33794a00-42b6-11eb-954a-8718f5445b19.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-12-20 08:09:53
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 547, in _onBridgeCmd
  File "</Applications/Anki 2.1.35.app/Contents/MacOS/decorator.pyc:decorator-gen-70>", line 2, in _linkHandler
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/jaredgordon/Library/Application Support/Anki2/addons21/review_heatmap/links.py", line 81, in heatmapLinkHandler
    invokeBrowser(arg)
  File "/Users/jaredgordon/Library/Application Support/Anki2/addons21/review_heatmap/links.py", line 108, in invokeBrowser
    browser.form.searchEdit.lineEdit().setText(search)
AttributeError: 'NoneType' object has no attribute 'form'
```

**Comment by glutanimate** [comment]
Thanks a bunch for the report! This should now be fixed in the `main` branch.
