### ISSUE TITLE
Getting an Error when I open "browse" section.

### ISSUE THREAD

**Issue by airdroptr1** [glutanimate/speed-focus-mode#38]
#### Problem description

Hi, firstly I wanted to thank you for this perfect addon and for your all efforts. I got this error when I click "b" or when I open "browse" section on anki. After this is error I can continue studying but whenever I click "b" to search some of my flashcards I see this error. And l use browse section as a library so I use it too much :) I hope you can solve it soon :) Thanks in advance.
 

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: macOS
- version:  big sur 

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

<img width="562" alt="Screenshot 2021-04-19 at 12 20 51" src="https://user-images.githubusercontent.com/36513755/115221266-c3ff5400-a109-11eb-881f-35d9130d1b14.png">

#### Error message (if any)

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you’ve discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-15 14:25:41

Caught exception:
Traceback (most recent call last):
File “aqt/main.py”, line 1067, in onBrowse
File “”, line 2, in open
File “anki/hooks.py”, line 89, in decorator_wrapper
File “anki/hooks.py”, line 81, in repl
TypeError: onDialogOpened() got an unexpected keyword argument ‘card’

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi there, thanks for the detailed report :)

Speed Focus Mode does not modify the browser, so the error you're seeing is almost certainly produced by another add-on or Anki itself (if there isn't an incredibly weird interaction going on).

Please try disabling all add-ons other than SFM, restart Anki, draw up the browser, and see if the error still appears. If not, then a different add-on is likely the issue, and my suggestion would be to try walking through them one by one (or in batches and then narrow it down) to find where the error is produced.

**Comment by glutanimate** [comment]
Nevermind, please scratch that last comment. While SFM does not modify the browser, it does interact with the code that opens up dialogs like the card browser, and it appears that there was a change under the hood in Anki 2.1.4x that SFM still needs to be adjusted for.

Thanks for letting me know! Added this to my TODO list to look into.

**Comment by glutanimate** [comment]
OK, pushed a change in 9307bee5e712bd6020eb8b503eac8ddfccba0c88 that should address this. Thankfully only the beta release is affected, the AnkiWeb release works fine.

Created a quick build of the updated version here: 

[speed-focus-mode-v0.4.0-beta.1-9-g9307bee-anki21.zip](https://github.com/glutanimate/speed-focus-mode/files/6335723/speed-focus-mode-v0.4.0-beta.1-9-g9307bee-anki21.zip) (please unzip the archive to get to the .ankiaddon file)

Would you mind giving it a try and letting me know if it fixes the issue for you? Thanks!

**Comment by airdroptr1** [comment]
Hi Glutanimate,

Sorry for the late reply, I deleted the addon and installed the one you
have sent and it worked out :). Thanks so much for your fast reaction and
answer.

By the way I have a suggestion, can you add the control of sound speed in
this addon ? Normally in windows I was using another add-on (and if you
like I can send you the add-on number ) in but it doesn't work in MacBook
and I cannot reach them author :(   They are not perfect as you are :) I am
learning German and in some flashcard groups I really need to change the
speed of the sound:)

Anyway you solved my problem and thanks again. Have a nice day.

Best regards
Jackson


Aristotelis ***@***.***>, 19 Nis 2021 Pzt, 13:43 tarihinde
şunu yazdı:

**Comment by felipemldias** [comment]
I get this error message when I try to open the browser from the heatmap addon for some reason =/

**Comment by DavidJayLeonard** [comment]
> OK, pushed a change in [9307bee](https://github.com/glutanimate/speed-focus-mode/commit/9307bee5e712bd6020eb8b503eac8ddfccba0c88) that should address this. Thankfully only the beta release is affected, the AnkiWeb release works fine.
> 
> Created a quick build of the updated version here:
> 
> [speed-focus-mode-v0.4.0-beta.1-9-g9307bee-anki21.zip](https://github.com/glutanimate/speed-focus-mode/files/6335723/speed-focus-mode-v0.4.0-beta.1-9-g9307bee-anki21.zip) (please unzip the archive to get to the .ankiaddon file)
> 
> Would you mind giving it a try and letting me know if it fixes the issue for you? Thanks!

I was having the same issue and this resolved it! Thank you @glutanimate!!
