### ISSUE TITLE
No longer works with 2.1.54

### ISSUE THREAD

**Issue by ama12321** [glutanimate/speed-focus-mode#49]
#### Problem description
Add-on throws error when starting with 2.1.54 new M1 update for Mac. 

"
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Speed Focus Mode auto-alert auto-reveal auto-fail/good⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/anthonyma/Library/Application Support/Anki2/addons21/1046608507/__init__.py", line 41, in <module>
    from . import main  # noqa: F401
  File "/Users/anthonyma/Library/Application Support/Anki2/addons21/1046608507/main.py", line 254, in <module>
    mw.form.menuTools.addAction('Pause speed focus mode', pause, 'P')
TypeError: arguments did not match any overloaded call:
  addAction(self, QIcon, str): argument 1 has unexpected type 'str'
  addAction(self, QIcon, str, PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'str'
  addAction(self, QIcon, str, Union[QKeySequence, QKeySequence.StandardKey, str, int]): argument 1 has unexpected type 'str'
  addAction(self, QIcon, str, Union[QKeySequence, QKeySequence.StandardKey, str, int], PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'str'
  addAction(self, str): too many arguments
  addAction(self, str, Union[QKeySequence, QKeySequence.StandardKey, str, int]): argument 2 has unexpected type 'function'
  addAction(self, str, PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 3 has unexpected type 'str'
  addAction(self, str, Union[QKeySequence, QKeySequence.StandardKey, str, int], PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 2 has unexpected type 'function'
  addAction(self, QAction): argument 1 has unexpected type 'str'
⁩"

Loved using the add on previously, would be awesome to get it updated for the new version.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi there, thanks for the report!

Based on the error message, it looks like you're using an unofficial version of the add-on. If you switch to the [AnkiWeb version](https://ankiweb.net/shared/info/1046608507), or the [latest beta from GitHub](https://github.com/glutanimate/speed-focus-mode/releases/download/v0.4.0-beta.1/speed-focus-mode-v0.4.0-beta.1-anki21.ankiaddon), the error message should no longer pop up.

Hope that helps!

**Comment by ama12321** [comment]
Thanks, I reinstalled from Ankiweb and there's no errors anymore. Sorry about the confusion, I had downloaded the addon from the Anking addons, maybe that was an older version. Thanks for the quick reply and the awesome work!

**Comment by glutanimate** [comment]
Happy to hear it works, and thanks for the kind words! :)
