### ISSUE TITLE
More Time Button and pause timer key missing

### ISSUE THREAD

**Issue by VinceCold** [glutanimate/speed-focus-mode#59]
#### Problem description

The "More Time!" button is absent when studying cards. The timer settings for flipping the card and for rating again tick with no problem, and the settings menu is readily accessed using Shift+Options, but there is no way to set the pause timer key, pressing the 'p' key does not pause the timer, and there is also no config file in the file directory of the addon. It almost seems like the add-on page on the Anki website is still linking to an older version?

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-02-01 10:14:42
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2022-09-08T05:45, 'None', mod]
    Anki Killstreaks ['579111794', 2021-12-15T07:20, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T14:11, 'None', '']
    Pokmanki ['1041307953', 2022-12-04T23:29, 'None', '']
    Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2019-06-02T02:11, 'None', '']
    The KING of Button Add-ons ['374005964', 2022-12-19T17:21, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1041307953 1046608507 1771074083 374005964 579111794 831846358
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi there, thanks for the report! SFM v1.0.0 and higher are only compatible with Anki 2.1.55 and up, unfortunately. If you install SFM on an earlier Anki release, it will automatically select an older version of the add-on where some of the features you mentioned aren't present, yet. To quote from AnkiWeb:

> I realize that this is a bit confusing, but SFM versions 1.0.0 and higher are only compatible with Anki 2.1.55 and up (as delivering new features to older Anki versions is becoming ever more difficult with newer releases overhauling major parts of Anki's UI).
> 
> Upgrading to the latest Anki version, and then updating your add-ons (if Anki doesn't prompt you to do so automatically), should allow you to use the newest features of Speed Focus Mode. However, please be aware that some other add-ons might not fully support Anki 2.1.55 and up, yet.


 Hope that clarifies things!
